name: SAST - Semgrep

on:
  pull_request:
  push:
    branches: [ "main", "master" ]

permissions:
  contents: read
  security-events: write # публикуем SARIF в Security

jobs:
  semgrep:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Semgrep OSS
        uses: returntocorp/semgrep-action@v1
        with:
          config: >-
            p/ci
            p/javascript
            p/typescript
          generateSarif: "1"    # генерировать SARIF
          publishSarif: "1"     # отправлять в GitHub Security
          auditOn: push         # запускать аудит на push
          severity: "ERROR"     # ⚠ только ERROR считаем блокирующими, WARNING не ломает пайплайн
        env:
          SEMGREP_TIMEOUT: "300"

      - name: Fail if semgrep failed
        if: failure()
        run: exit 1
